'use strict';
/* Translation core. Keys are the Uzbek (Cyrillic) strings used in the code.
   - uz-Cyrl: key as is
   - uz-Latn: generated by transliteration
   - ru / en: dictionaries in i18n-ru.js and i18n-en.js
   Placeholders look like {name}. Missing keys fall back to Uzbek Cyrillic. */
const LANGS = {
  'uz-Cyrl': 'Ўзбекча (кирилл)',
  'uz-Latn': 'Oʻzbekcha (lotin)',
  ru: 'Русский',
  en: 'English'
};
let LANG = 'uz-Cyrl';
const DICT = { ru: {}, en: {} };

const LAT = {
  а: 'a', б: 'b', в: 'v', г: 'g', д: 'd', е: 'e', ё: 'yo', ж: 'j', з: 'z', и: 'i', й: 'y', к: 'k', л: 'l', м: 'm', н: 'n',
  о: 'o', п: 'p', р: 'r', с: 's', т: 't', у: 'u', ф: 'f', х: 'x', ц: 'ts', ч: 'ch', ш: 'sh', щ: 'shch', ъ: 'ʼ', ы: 'i',
  ь: '', э: 'e', ю: 'yu', я: 'ya', ў: 'oʻ', қ: 'q', ғ: 'gʻ', ҳ: 'h'
};
const VOWELS = /[аеёиоуэюяўы]/i;
function translit(s) {
  let out = '';
  for (let i = 0; i < s.length; i++) {
    const ch = s[i];
    const lo = ch.toLowerCase();
    let r = LAT[lo];
    if (r === undefined) { out += ch; continue; }
    if (lo === 'е') {
      const prev = s[i - 1];
      if (!prev || !/[а-яёўқғҳ]/i.test(prev) || VOWELS.test(prev)) r = 'ye';
    }
    if (ch !== lo && r) {
      const next = s[i + 1];
      const nextUpper = next && next !== next.toLowerCase();
      r = nextUpper ? r.toUpperCase() : r[0].toUpperCase() + r.slice(1);
    }
    out += r;
  }
  return out;
}
const latCache = new Map();
function tr(key, vars) {
  let s;
  if (LANG === 'ru') s = DICT.ru[key] ?? key;
  else if (LANG === 'en') s = DICT.en[key] ?? key;
  else if (LANG === 'uz-Latn') {
    s = latCache.get(key);
    if (s === undefined) { s = translit(key); latCache.set(key, s); }
  } else s = key;
  return vars ? s.replace(/\{(\w+)\}/g, (m, k) => (vars[k] ?? '')) : s;
}
